name: build_unittest

on: [push]

jobs:
  build-cmake-windows:
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.7']
    name: ${{ matrix.os }}-${{ matrix.python-version }}-CMake
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        pip install numpy
    - name: configure
      run: |
        ls env:
        mkdir target-Release
        cd target-Release
        cmake .. -DCMAKE_INSTALL_PREFIX=install${{ matrix.os }}CMake-Github -DPYTHON_VERSION=${{ matrix.python-version }} -DENABLE_SWIG=ON
        cd ..
        mkdir target-Debug
        cd target-Debug
        cmake .. -DCMAKE_INSTALL_PREFIX=install${{ matrix.os }}CMake-Github -DENABLE_PYTHON=OFF
    - name: build
      run: |
        cd target-Release
        cmake --build . --config Release -j
        cd ..
        cd target-Debug
        cmake --build . --config Debug -j
    - name: test
    # should run w/o install
      run: |
        cd target-Release
        ctest -C Release --output-on-failure
        cd ..
        cd target-Debug
        ctest -C Debug --output-on-failure
    - name: install
      run: |
        cd target-Release
        cmake --build . --config Release --target install
        cd ..
        cd target-Debug
        cmake --build . --config Debug --target install
        cd ..
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: msbuild
      run: |
        msbuild coda-oss.sln /p:configuration=Release
        msbuild coda-oss.sln /p:configuration=Debug
    #- name: mstest
    #  run: |
        # mstest /testcontainer:${RUNNER_WORKSPACE}\coda-oss\x64\Debug\UnitTest.dll

  build-linux-cmake:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7']
    name: ${{ matrix.os }}-${{ matrix.python-version }}-CMake
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        pip install numpy
    - name: configure
      run: |
        env
        which python
        mkdir target
        cd target
        cmake .. -DCMAKE_INSTALL_PREFIX=install${{ matrix.os }}CMake-Github -DPYTHON_VERSION=${{ matrix.python-version }} -DENABLE_SWIG=ON
    - name: build
      run: |
        cd target
        # "-j" spawns too many processes causing GCC to crash
        cmake --build . -j 12
    - name: test
    # should run w/o install
      run: |
        cd target
        ctest --output-on-failure
    - name: install
      run: |
        cd target
        cmake --build . --target install

  build-waf:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        python-version: ['3.7']
        debugging: ['--enable-debugging', '']
    name: ${{ matrix.os }}-${{ matrix.python-version }}-waf${{ matrix.debugging }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: configure_with_swig
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        pip install numpy
        mkdir install${{ matrix.os }}Waf-Github
        python waf configure --prefix="$PWD/install${{ matrix.os }}Waf-Github" --enable-swig ${{ matrix.debugging }}
    - name: configure_without_swig
      if: ${{ matrix.os == 'windows-2019' }}
      run: |
        pip install numpy
        mkdir install${{ matrix.os }}Waf-Github
        python waf configure --prefix="$PWD/install${{ matrix.os }}Waf-Github" ${{ matrix.debugging }}
    - name: build
      run: |
        python waf build
    - name: install
      run: |
        python waf install
    - name: test
      run: |
        python waf install --alltests

