name: Build, unittest

on:
  push:
    branches: main
  pull_request:
    branches: main


jobs:
  build-windows:
    name: Windows
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=installWindows-Github -DPYTHON_VERSION="3.7" ..
    - name: make
      run: |
        cd build
        cmake --build . --config Release -j
        cmake --build . --config Release --target install
    - name: test
      run: |
        cd build
        ctest -C Release

  build-linux:
    name: Linux
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=installLinux-Github -DPYTHON_VERSION=3.7 ..
    - name: make
      run: |
        cd build
        # using the default number of threads (-j) causes G++ to crash
        cmake --build . -j 2
        cmake --build . --target install
    - name: test
      run: |
        cd build
        ctest


